hb_handball_homepage:
    path:     /
    defaults: { _controller: HBHandballBundle:Posts:index }

hb_handball_add_post:
    path:     /ajout/post
    defaults: { _controller: HBHandballBundle:Posts:addPost }
    
hb_handball_add_category:
    path:     /ajout/category
    defaults: { _controller: HBHandballBundle:Posts:addCategory }

hb_handball_category:
    path:     /category
    defaults: { _controller: HBHandballBundle:Posts:category }
    
hb_handball_onlyOneCategory:
    path:     /category/{id}
    defaults: 
        _controller: HBHandballBundle:Posts:listPost 
        
hb_handball_onlyOne:
    path:     /post/{id}
    defaults: 
            _controller: HBHandballBundle:Posts:post 
        
hb_handball_updatePost:
    path:     /post/modification/{id}
    defaults: 
            _controller: HBHandballBundle:Posts:update
            
hb_handball_search:
    path:     /recherche
    defaults: 
            _controller: HBHandballBundle:Posts:search