hb_handball_homepage:
    path:     /
    defaults: { _controller: HBHandballBundle:Posts:index }

hb_handball_add_post:
    path:     /ajout/post
    defaults: { _controller: HBHandballBundle:Admin:addPost }
    
hb_handball_add_category:
    path:     /ajout/category
    defaults: { _controller: HBHandballBundle:Admin:addCategory }

hb_handball_category:
    path:     /category
    defaults: { _controller: HBHandballBundle:Posts:category }
    
hb_handball_onlyOneCategory:
    path:     /category/{id}/page/{page}
    defaults: 
        _controller: HBHandballBundle:Posts:listPost 
        
hb_handball_onlyOne:
    path:     /post/{id}
    defaults: 
            _controller: HBHandballBundle:Posts:post 
        
hb_handball_updatePost:
    path:     /post/modification/{id}
    defaults: 
            _controller: HBHandballBundle:Admin:update
            
hb_handball_search:
    path:     /recherche
    defaults: 
            _controller: HBHandballBundle:Posts:search

hb_handball_search2:
    path:     /recherche/{recherche}/page/{page}
    defaults: 
            _controller: HBHandballBundle:Posts:search2
            
hb_handball_admin:
    path:     /administration
    defaults: 
            _controller: HBHandballBundle:Admin:admin
            
hb_handball_delete:
    path:     /supprimer/{id}
    defaults: 
            _controller: HBHandballBundle:Admin:delete
            
            
hb_handball_category_admin:
    path:     /admin/category
    defaults: { _controller: HBHandballBundle:Admin:category }
    
hb_handball_category_update:
    path:     /admin/category/modification/{id}
    defaults: { _controller: HBHandballBundle:Admin:updateCategory }
    
hb_handball_category_delete:
    path:     /admin/category/supprimer/{id}
    defaults: { _controller: HBHandballBundle:Admin:deleteCategory }